#!/bin/sh
#
# Start OPC server
#
 
 
start() {
        echo -n "Starting backend OPC server..."
        /var/opc/relay/relay.py &
        echo "OK"
}

stop() {
        echo -n "Stopping OPC Server"
        kill -9 $(ps aux | grep 'relay.py' | awk '{print $1}') &> /dev/null
        echo "OK"
}
restart() {
        stop
        start
}
 
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
 
exit $?
