import datetime
import random
from PyOPC.OPCContainers import *

# Initial timestamp for all ItemValues
def_ts = datetime.datetime(2006, 2, 15, 12, 15, 18)

WTCOPCItems = ((ItemContainer(ItemName='PS2_PUMP_0',
                               Value=1,
                               Timestamp=def_ts,
                               QualityField='good',
                               LimitField='none',
                               VendorField=0),
                 (OPCProperty(Name='accessRights',
                              Value='readWritable'),
                  OPCProperty(Name='description',
                              Value='Pumping Station 3 Pump 1'))),
                (ItemContainer(ItemName='PS2_PUMP_1',
                               Value=1,
                               Timestamp=def_ts,
                               QualityField='good',
                               LimitField='none',
                               VendorField=0),
                 (OPCProperty(Name='accessRights',
                              Value='readWritable'),
                  OPCProperty(Name='description',
                              Value='Pumping Station 3 Backup Pumpe'))),
               (ItemContainer(ItemName='PS2_VALVE_0',
                               Value=1,
                               Timestamp=def_ts,
                               QualityField='good',
                               LimitField='none',
                               VendorField=0),
                 (OPCProperty(Name='accessRights',
                              Value='readWritable'),
                  OPCProperty(Name='description',
                              Value='Pumping Station 3 Valve 0'))),
                 (ItemContainer(ItemName='PS2_VALVE_1',
                               Value=1,
                               Timestamp=def_ts,
                               QualityField='good',
                               LimitField='none',
                               VendorField=0),
                 (OPCProperty(Name='accessRights',
                              Value='readWritable'),
                  OPCProperty(Name='description',
                              Value='Pumping Station 3 Valve 2'))),
				(ItemContainer(ItemName='PS2_CHLOR',
                               Value=1,
                               Timestamp=def_ts,
                               QualityField='good',
                               LimitField='none',
                               VendorField=0),
                 (OPCProperty(Name='accessRights',
                              Value='readWritable'),
				  OPCProperty(Name='description',
                              Value='Pumping Station 3 Chlorine Tank'))))
