#Test Tags to see if this is actually working
#Syntax (name, failValue, cmp_op, [previous_nodes], [next_nodes], startValue, track)
tags = [('PS0_VALVE_0', '0', '==', None, ['PS0_CHLOR'], '1', False),
		('PS0_VALVE_1', '0', '==', None, ['PS0_CHLOR'], '1', False),
		('PS0_CHLOR', '0', '==', ['PS0_VALVE_0','PS0_VALVE_1'], ['TC0_SULF_ACID', 'TC0_FERR_CH'], '1', True),
		('PS0_DEST_NET', '0', '==', None, ['TC0_PUMP_0'], '1', False),
		('TC0_PUMP_0', '0', '==', None, ['TC0_SULF_ACID', 'TC0_FERR_CH'], '1', False),
		('TC0_SULF_ACID', '0', '==', ['TC0_PUMP_0'], ['TC0_OZONE', 'TC0_VALVE_4', 'TC0_VALVE_5', 'TC0_VALVE_6'], '1', True),
		('TC0_FERR_CH', '0', '==', ['TC0_PUMP_0'], ['TC0_OZONE'], '1', True),
		('TC0_PUMP_1', '0', '==', None, ['TC0_OZONE', 'TC0_SOD_BI'], '1', False),
		('TC0_OZONE', '0', '==', ['TC0_PUMP_1'], ['TC0_SOD_BI'], '1', True),
		('TC0_SOD_BI', '0', '==', ['TC0_PUMP_1'], ['TC0_CHLORINE', 'TC0_SOD_HYDRO'], '1', True),
		('TC0_VALVE_2', '0', '==', None, ['TC0_CHLORINE', 'TC0_SOD_HYDRO'], '1', False),
		('TC0_VALVE_3', '0', '==', None, ['TC0_CHLORINE', 'TC0_SOD_HYDRO'], '1', False),
		('TC0_CHLORINE', '0', '==', ['TC0_VALVE_2', 'TC0_VALVE_3'], ['TC0_UV0', 'TC0_UV1', 'TC0_UV2'], '1', True),
		('TC0_SOD_HYDRO', '0', '==', ['TC0_VALVE_2', 'TC0_VALVE_3'], ['TC0_UV0', 'TC0_UV1', 'TC0_UV2'], '1', True),
		('TC0_VALVE_4', '0', '==', None, ['TC0_UV0'], '1', False),
		('TC0_VALVE_5', '0', '==', None, ['TC0_UV1'], '1', False),
		('TC0_VALVE_6', '0', '==', None, ['TC0_UV2'], '1', False),
		('TC0_UV0', '0', '==', ['TC0_VALVE_4'], ['TC0_FLOUR', 'TC0_ORTHO_PHOS'], '1', True), 
		('TC0_UV1', '0', '==', ['TC0_VALVE_5'], ['TC0_FLOUR', 'TC0_ORTHO_PHOS'], '1', True),
		('TC0_UV2', '0', '==', ['TC0_VALVE_6'], ['TC0_FLOUR', 'TC0_ORTHO_PHOS'], '1', True),
		('TC0_FLOUR', '0', '==', ['TC0_VALVE_4', 'TC0_VALVE_5', 'TC0_VALVE_6'], ['TC0_DEST_NET'], '1', True),
		('TC0_ORTHO_PHOS', '0', '==', ['TC0_VALVE_4', 'TC0_VALVE_5', 'TC0_VALVE_6'], ['TC0_DEST_NET'], '1', True),
		('TC0_DEST_NET', '0', '==', None, ['PS1_CHLOR'], '1', False),
		('PS1_VALVE_0', '0', '==', None, ['PS1_CHLOR'], '1', False),
		('PS1_VALVE_1', '0', '==', None, ['PS1_CHLOR'], '1', False),
		('PS1_CHLOR', '0', '==', ['PS1_VALVE_0', 'PS1_VALVE_1'], ['PS2_CHLOR', 'PS3_CHLOR'], '1', True),
		('PS2_VALVE_0', '0', '==', None, ['PS2_CHLOR'], '1', False),
		('PS2_VALVE_1', '0', '==', None, ['PS2_CHLOR'], '1', False),
		('PS2_CHLOR', '0', '==', ['PS2_VALVE_0', 'PS2_VALVE_1'], ['PS4_CHLOR'], '1', True),
		('PS3_VALVE_0', '0', '==', None, ['PS3_CHLOR'], '1', False),
		('PS3_VALVE_1', '0', '==', None, ['PS3_CHLOR'], '1', False),
		('PS3_CHLOR', '0', '==', ['PS3_VALVE_0', 'PS3_VALVE_1'], ['PS5_CHLOR'], '1', True),
		('PS4_VALVE_0', '0', '==', None, ['PS4_CHLOR'], '1', False),
		('PS4_VALVE_1', '0', '==', None, ['PS4_CHLOR'], '1', False),
		('PS4_CHLOR', '0', '==', ['PS4_VALVE_0', 'PS4_VALVE_1'], ['PS5_CHLOR'], '1', True),
		('PS5_VALVE_0', '0', '==', None, ['PS5_CHLOR'], '1', False),
		('PS5_VALVE_1', '0', '==', None, ['PS5_CHLOR'], '1', False),
		('PS5_CHLOR', '0', '==', ['PS5_VALVE_0', 'PS5_VALVE_1'], ['PS5_DEST_NET'], '1', True),
		('PS5_DEST_NET', '0', '==', ['PS5_CHLOR'], None, '1', False)]
