#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
 	echo "Starting network..."
	/sbin/ifconfig eth1 10.1.2.1 netmask 255.255.255.0
	;;
  stop)
	printf "Stopping network..."
	/sbin/ifconfig eth1 down
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

